### ISSUE TITLE
Magento 1 not working

### ISSUE THREAD

**Issue by panteliskopsias** [business-factory/roi-hunter-easy-magento1-plugin#12]
For over 1 year now the plugin stop work with the error code when i try to open  it from backend
raven.js:432 Uncaught Error: Shopify Products preview url parameter is empty.
    at validateShopifyInitialMessage (ShopifyAppMessageValidator.tsx:8)
    at App._this.receiveMessage (App.tsx:193)
    at d (raven.js:428)

Is any solution for that?
It was very nice plugin....

**Comment by Vergil333** [comment]
Hello @panteliskopsias. Plugins for Magento platforms are not supported for over 2 years now and are deprecated. In the future we are planing to release new Magento plugin.
